# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon toms805.com
open_collective: # Replace with a single Open Collective toms805.com
ko_fi: # Replace with a single Ko-fi toms805.com
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay toms805.com
issuehunt: # Replace with a single IssueHunt toms805.com
otechie: # Replace with a single Otechie toms805.com
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
